### ISSUE TITLE
ChannelMath cannot be GPL because of incompatibility with CPL

### ISSUE THREAD

**Issue by devernay** [NatronVFX/openfx-plugins#1]
Be careful that ChannelMath uses the exprtk library which is CPL.
CPL is not GPL compatible https://en.wikipedia.org/wiki/Common_Public_License

**Comment by olear** [comment]
I know, I just added the plugin. And in source form we don't violate anything.

ChannelMath is based on code (plugin structure) from your repository, so we can't change the licence on the actual plugin.

**Comment by ArashPartow** [comment]
As mentioned [here](https://github.com/devernay/openfx-misc/pull/43#issuecomment-244380834), if you decide to use ExprTk, I'd be more than happy to provide either a Boost or MIT license, which I think is _compatible_ with GPL.

**Comment by olear** [comment]
Thanks, both Boost and MIT are compatible with the GPL.

**Comment by devernay** [comment]
@ArashPartow we're seriously considering using exprtk as a simple expression language inside Natron (most expressions don't require python).
Could you distribute it under a boost or MIT licence as you proposed?
We would probably also modify it a bit so that when an unknown variable is encountered in the expression, it calls a  callback that may define the variable on-the-fly (since we have hundreds of variables in the application and don't want to declare them all). Or do you prefer to do that modification yourself?
Cc: @MrKepzie

**Comment by ArashPartow** [comment]
@devernay  I've re-licensed the library under MIT a few weeks ago.

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L113

----------------

With regards to unknown variables, please have a read of the following section of the documentation:

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L2662

and also have a review of the following example in the test suite:

https://github.com/ArashPartow/exprtk/blob/master/exprtk_test.cpp#L7615

I believe both those points should cover your use-case and most likely will not require any modifications to the library itself.

**Comment by MrKepzie** [comment]
@ArashPartow Is there any way to force a loop control flow to return at some point ? We need to evaluate the expression in the GUI thread and we would't want the user by mistake to produce an infinite loop and hang the application.

**Comment by devernay** [comment]
I think the easiest solution is:
in exprtk.hpp, just replace every instance of `while (is_true(condition_))` with `while (is_true(condition_) && !loop_exit())` where loop_exit() could be a macro defined to false by default, which you could replace by any other definition:
```
// at the beginning of exprtk.hpp
#ifndef loop_exit
#define loop_exit() (false)
#endif
```

**Comment by MrKepzie** [comment]
@ArashPartow Further questions if you don't mind:

1) In Natron we provide expressions for string parameters: typically the user would want the value of a text parameter to be the string representation of the current frame in the timeline.

Say I pre-declare a string variable named "frame":
    
     typedef exprtk::symbol_table<double>  symbol_table_t;
     symbol_table_t symbol_table;
     symbol_table.add_stringvar("frame", frame);

Ideally I would like the user to write an expression as simple as:

    frame


exprtk has string variables, however it seems impossible for the return type of the expression to be a string (I guess because each statement has a result).
The only solution seems to declare a string variable where to store the result, and then fetch it once the expression is evaluated:
    
    std::string ret;
    symbol_table.add_stringvar("ret", ret);
    ...
    ret = symbol_table.stringvar_ref("ret");

Same question for vectors, is it possible to return a vector ?


2) I about the unknown unknowns and it seems to correspond to our needs, however the unresolved symbol resolver objet seems to only work for scalar variables but we may have undefined string variables as well. Can this be extended for string variables ?

3) An expression may well be evaluated concurrently by multiple *render* threads and generally in a very performance critical code section.
We may only know variable values at the time we need to evaluate the expression.

Is this correct to do as following:

* create a symbol_table, parser and expression on the main thread when the user set the expression
with *stub* variables just to get the expression to compile

* get rid of the parser object that was created (I don't think a reference is kept anywhere inside the expression)
* copy the expression at evaluation time (in the *render* thread), update the variables in the symbol_table to their actual value with *expression.get_symbol_table(0).variable_ref("variable")* and then just call 

    expression.value()

**Comment by ArashPartow** [comment]
@MrKepzie MrKepzie

> Is there any way to force a loop control flow to return at some point ? 

There is no way to achieve that as-is.  @devernay  solution seems to be ok - though that now means all expressions will be affected by that new loop variable variable.

**Comment by ArashPartow** [comment]
@MrKepzie  wrt returning values from an Expression please review Section 20 - Expression Return Values:

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L3249
